# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wangk/code/cpp/sylar/code/my_sylar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wangk/code/cpp/sylar/code/my_sylar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangk/code/cpp/sylar/code/my_sylar/CMakeFiles /home/wangk/code/cpp/sylar/code/my_sylar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangk/code/cpp/sylar/code/my_sylar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testScheduler

# Build rule for target.
testScheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testScheduler
.PHONY : testScheduler

# fast build rule for target.
testScheduler/fast:
	$(MAKE) -f CMakeFiles/testScheduler.dir/build.make CMakeFiles/testScheduler.dir/build
.PHONY : testScheduler/fast

#=============================================================================
# Target rules for targets named testLog

# Build rule for target.
testLog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testLog
.PHONY : testLog

# fast build rule for target.
testLog/fast:
	$(MAKE) -f CMakeFiles/testLog.dir/build.make CMakeFiles/testLog.dir/build
.PHONY : testLog/fast

#=============================================================================
# Target rules for targets named testThread

# Build rule for target.
testThread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testThread
.PHONY : testThread

# fast build rule for target.
testThread/fast:
	$(MAKE) -f CMakeFiles/testThread.dir/build.make CMakeFiles/testThread.dir/build
.PHONY : testThread/fast

#=============================================================================
# Target rules for targets named sylar

# Build rule for target.
sylar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sylar
.PHONY : sylar

# fast build rule for target.
sylar/fast:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/build
.PHONY : sylar/fast

#=============================================================================
# Target rules for targets named testStack

# Build rule for target.
testStack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testStack
.PHONY : testStack

# fast build rule for target.
testStack/fast:
	$(MAKE) -f CMakeFiles/testStack.dir/build.make CMakeFiles/testStack.dir/build
.PHONY : testStack/fast

#=============================================================================
# Target rules for targets named testConfig

# Build rule for target.
testConfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testConfig
.PHONY : testConfig

# fast build rule for target.
testConfig/fast:
	$(MAKE) -f CMakeFiles/testConfig.dir/build.make CMakeFiles/testConfig.dir/build
.PHONY : testConfig/fast

#=============================================================================
# Target rules for targets named testFiber

# Build rule for target.
testFiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testFiber
.PHONY : testFiber

# fast build rule for target.
testFiber/fast:
	$(MAKE) -f CMakeFiles/testFiber.dir/build.make CMakeFiles/testFiber.dir/build
.PHONY : testFiber/fast

sylar/config.o: sylar/config.cpp.o

.PHONY : sylar/config.o

# target to build an object file
sylar/config.cpp.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/config.cpp.o
.PHONY : sylar/config.cpp.o

sylar/config.i: sylar/config.cpp.i

.PHONY : sylar/config.i

# target to preprocess a source file
sylar/config.cpp.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/config.cpp.i
.PHONY : sylar/config.cpp.i

sylar/config.s: sylar/config.cpp.s

.PHONY : sylar/config.s

# target to generate assembly for a file
sylar/config.cpp.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/config.cpp.s
.PHONY : sylar/config.cpp.s

sylar/fiber.o: sylar/fiber.cpp.o

.PHONY : sylar/fiber.o

# target to build an object file
sylar/fiber.cpp.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fiber.cpp.o
.PHONY : sylar/fiber.cpp.o

sylar/fiber.i: sylar/fiber.cpp.i

.PHONY : sylar/fiber.i

# target to preprocess a source file
sylar/fiber.cpp.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fiber.cpp.i
.PHONY : sylar/fiber.cpp.i

sylar/fiber.s: sylar/fiber.cpp.s

.PHONY : sylar/fiber.s

# target to generate assembly for a file
sylar/fiber.cpp.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/fiber.cpp.s
.PHONY : sylar/fiber.cpp.s

sylar/log.o: sylar/log.cpp.o

.PHONY : sylar/log.o

# target to build an object file
sylar/log.cpp.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/log.cpp.o
.PHONY : sylar/log.cpp.o

sylar/log.i: sylar/log.cpp.i

.PHONY : sylar/log.i

# target to preprocess a source file
sylar/log.cpp.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/log.cpp.i
.PHONY : sylar/log.cpp.i

sylar/log.s: sylar/log.cpp.s

.PHONY : sylar/log.s

# target to generate assembly for a file
sylar/log.cpp.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/log.cpp.s
.PHONY : sylar/log.cpp.s

sylar/macro.o: sylar/macro.cpp.o

.PHONY : sylar/macro.o

# target to build an object file
sylar/macro.cpp.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/macro.cpp.o
.PHONY : sylar/macro.cpp.o

sylar/macro.i: sylar/macro.cpp.i

.PHONY : sylar/macro.i

# target to preprocess a source file
sylar/macro.cpp.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/macro.cpp.i
.PHONY : sylar/macro.cpp.i

sylar/macro.s: sylar/macro.cpp.s

.PHONY : sylar/macro.s

# target to generate assembly for a file
sylar/macro.cpp.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/macro.cpp.s
.PHONY : sylar/macro.cpp.s

sylar/mutex.o: sylar/mutex.cpp.o

.PHONY : sylar/mutex.o

# target to build an object file
sylar/mutex.cpp.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/mutex.cpp.o
.PHONY : sylar/mutex.cpp.o

sylar/mutex.i: sylar/mutex.cpp.i

.PHONY : sylar/mutex.i

# target to preprocess a source file
sylar/mutex.cpp.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/mutex.cpp.i
.PHONY : sylar/mutex.cpp.i

sylar/mutex.s: sylar/mutex.cpp.s

.PHONY : sylar/mutex.s

# target to generate assembly for a file
sylar/mutex.cpp.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/mutex.cpp.s
.PHONY : sylar/mutex.cpp.s

sylar/scheduler.o: sylar/scheduler.cpp.o

.PHONY : sylar/scheduler.o

# target to build an object file
sylar/scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/scheduler.cpp.o
.PHONY : sylar/scheduler.cpp.o

sylar/scheduler.i: sylar/scheduler.cpp.i

.PHONY : sylar/scheduler.i

# target to preprocess a source file
sylar/scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/scheduler.cpp.i
.PHONY : sylar/scheduler.cpp.i

sylar/scheduler.s: sylar/scheduler.cpp.s

.PHONY : sylar/scheduler.s

# target to generate assembly for a file
sylar/scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/scheduler.cpp.s
.PHONY : sylar/scheduler.cpp.s

sylar/thread.o: sylar/thread.cpp.o

.PHONY : sylar/thread.o

# target to build an object file
sylar/thread.cpp.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/thread.cpp.o
.PHONY : sylar/thread.cpp.o

sylar/thread.i: sylar/thread.cpp.i

.PHONY : sylar/thread.i

# target to preprocess a source file
sylar/thread.cpp.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/thread.cpp.i
.PHONY : sylar/thread.cpp.i

sylar/thread.s: sylar/thread.cpp.s

.PHONY : sylar/thread.s

# target to generate assembly for a file
sylar/thread.cpp.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/thread.cpp.s
.PHONY : sylar/thread.cpp.s

sylar/util.o: sylar/util.cpp.o

.PHONY : sylar/util.o

# target to build an object file
sylar/util.cpp.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/util.cpp.o
.PHONY : sylar/util.cpp.o

sylar/util.i: sylar/util.cpp.i

.PHONY : sylar/util.i

# target to preprocess a source file
sylar/util.cpp.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/util.cpp.i
.PHONY : sylar/util.cpp.i

sylar/util.s: sylar/util.cpp.s

.PHONY : sylar/util.s

# target to generate assembly for a file
sylar/util.cpp.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/sylar/util.cpp.s
.PHONY : sylar/util.cpp.s

tests/testConfig.o: tests/testConfig.cpp.o

.PHONY : tests/testConfig.o

# target to build an object file
tests/testConfig.cpp.o:
	$(MAKE) -f CMakeFiles/testConfig.dir/build.make CMakeFiles/testConfig.dir/tests/testConfig.cpp.o
.PHONY : tests/testConfig.cpp.o

tests/testConfig.i: tests/testConfig.cpp.i

.PHONY : tests/testConfig.i

# target to preprocess a source file
tests/testConfig.cpp.i:
	$(MAKE) -f CMakeFiles/testConfig.dir/build.make CMakeFiles/testConfig.dir/tests/testConfig.cpp.i
.PHONY : tests/testConfig.cpp.i

tests/testConfig.s: tests/testConfig.cpp.s

.PHONY : tests/testConfig.s

# target to generate assembly for a file
tests/testConfig.cpp.s:
	$(MAKE) -f CMakeFiles/testConfig.dir/build.make CMakeFiles/testConfig.dir/tests/testConfig.cpp.s
.PHONY : tests/testConfig.cpp.s

tests/testFiber.o: tests/testFiber.cpp.o

.PHONY : tests/testFiber.o

# target to build an object file
tests/testFiber.cpp.o:
	$(MAKE) -f CMakeFiles/testFiber.dir/build.make CMakeFiles/testFiber.dir/tests/testFiber.cpp.o
.PHONY : tests/testFiber.cpp.o

tests/testFiber.i: tests/testFiber.cpp.i

.PHONY : tests/testFiber.i

# target to preprocess a source file
tests/testFiber.cpp.i:
	$(MAKE) -f CMakeFiles/testFiber.dir/build.make CMakeFiles/testFiber.dir/tests/testFiber.cpp.i
.PHONY : tests/testFiber.cpp.i

tests/testFiber.s: tests/testFiber.cpp.s

.PHONY : tests/testFiber.s

# target to generate assembly for a file
tests/testFiber.cpp.s:
	$(MAKE) -f CMakeFiles/testFiber.dir/build.make CMakeFiles/testFiber.dir/tests/testFiber.cpp.s
.PHONY : tests/testFiber.cpp.s

tests/testLog.o: tests/testLog.cpp.o

.PHONY : tests/testLog.o

# target to build an object file
tests/testLog.cpp.o:
	$(MAKE) -f CMakeFiles/testLog.dir/build.make CMakeFiles/testLog.dir/tests/testLog.cpp.o
.PHONY : tests/testLog.cpp.o

tests/testLog.i: tests/testLog.cpp.i

.PHONY : tests/testLog.i

# target to preprocess a source file
tests/testLog.cpp.i:
	$(MAKE) -f CMakeFiles/testLog.dir/build.make CMakeFiles/testLog.dir/tests/testLog.cpp.i
.PHONY : tests/testLog.cpp.i

tests/testLog.s: tests/testLog.cpp.s

.PHONY : tests/testLog.s

# target to generate assembly for a file
tests/testLog.cpp.s:
	$(MAKE) -f CMakeFiles/testLog.dir/build.make CMakeFiles/testLog.dir/tests/testLog.cpp.s
.PHONY : tests/testLog.cpp.s

tests/testScheduler.o: tests/testScheduler.cpp.o

.PHONY : tests/testScheduler.o

# target to build an object file
tests/testScheduler.cpp.o:
	$(MAKE) -f CMakeFiles/testScheduler.dir/build.make CMakeFiles/testScheduler.dir/tests/testScheduler.cpp.o
.PHONY : tests/testScheduler.cpp.o

tests/testScheduler.i: tests/testScheduler.cpp.i

.PHONY : tests/testScheduler.i

# target to preprocess a source file
tests/testScheduler.cpp.i:
	$(MAKE) -f CMakeFiles/testScheduler.dir/build.make CMakeFiles/testScheduler.dir/tests/testScheduler.cpp.i
.PHONY : tests/testScheduler.cpp.i

tests/testScheduler.s: tests/testScheduler.cpp.s

.PHONY : tests/testScheduler.s

# target to generate assembly for a file
tests/testScheduler.cpp.s:
	$(MAKE) -f CMakeFiles/testScheduler.dir/build.make CMakeFiles/testScheduler.dir/tests/testScheduler.cpp.s
.PHONY : tests/testScheduler.cpp.s

tests/testStack.o: tests/testStack.cpp.o

.PHONY : tests/testStack.o

# target to build an object file
tests/testStack.cpp.o:
	$(MAKE) -f CMakeFiles/testStack.dir/build.make CMakeFiles/testStack.dir/tests/testStack.cpp.o
.PHONY : tests/testStack.cpp.o

tests/testStack.i: tests/testStack.cpp.i

.PHONY : tests/testStack.i

# target to preprocess a source file
tests/testStack.cpp.i:
	$(MAKE) -f CMakeFiles/testStack.dir/build.make CMakeFiles/testStack.dir/tests/testStack.cpp.i
.PHONY : tests/testStack.cpp.i

tests/testStack.s: tests/testStack.cpp.s

.PHONY : tests/testStack.s

# target to generate assembly for a file
tests/testStack.cpp.s:
	$(MAKE) -f CMakeFiles/testStack.dir/build.make CMakeFiles/testStack.dir/tests/testStack.cpp.s
.PHONY : tests/testStack.cpp.s

tests/testThread.o: tests/testThread.cpp.o

.PHONY : tests/testThread.o

# target to build an object file
tests/testThread.cpp.o:
	$(MAKE) -f CMakeFiles/testThread.dir/build.make CMakeFiles/testThread.dir/tests/testThread.cpp.o
.PHONY : tests/testThread.cpp.o

tests/testThread.i: tests/testThread.cpp.i

.PHONY : tests/testThread.i

# target to preprocess a source file
tests/testThread.cpp.i:
	$(MAKE) -f CMakeFiles/testThread.dir/build.make CMakeFiles/testThread.dir/tests/testThread.cpp.i
.PHONY : tests/testThread.cpp.i

tests/testThread.s: tests/testThread.cpp.s

.PHONY : tests/testThread.s

# target to generate assembly for a file
tests/testThread.cpp.s:
	$(MAKE) -f CMakeFiles/testThread.dir/build.make CMakeFiles/testThread.dir/tests/testThread.cpp.s
.PHONY : tests/testThread.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... testScheduler"
	@echo "... testLog"
	@echo "... testThread"
	@echo "... sylar"
	@echo "... testStack"
	@echo "... testConfig"
	@echo "... testFiber"
	@echo "... sylar/config.o"
	@echo "... sylar/config.i"
	@echo "... sylar/config.s"
	@echo "... sylar/fiber.o"
	@echo "... sylar/fiber.i"
	@echo "... sylar/fiber.s"
	@echo "... sylar/log.o"
	@echo "... sylar/log.i"
	@echo "... sylar/log.s"
	@echo "... sylar/macro.o"
	@echo "... sylar/macro.i"
	@echo "... sylar/macro.s"
	@echo "... sylar/mutex.o"
	@echo "... sylar/mutex.i"
	@echo "... sylar/mutex.s"
	@echo "... sylar/scheduler.o"
	@echo "... sylar/scheduler.i"
	@echo "... sylar/scheduler.s"
	@echo "... sylar/thread.o"
	@echo "... sylar/thread.i"
	@echo "... sylar/thread.s"
	@echo "... sylar/util.o"
	@echo "... sylar/util.i"
	@echo "... sylar/util.s"
	@echo "... tests/testConfig.o"
	@echo "... tests/testConfig.i"
	@echo "... tests/testConfig.s"
	@echo "... tests/testFiber.o"
	@echo "... tests/testFiber.i"
	@echo "... tests/testFiber.s"
	@echo "... tests/testLog.o"
	@echo "... tests/testLog.i"
	@echo "... tests/testLog.s"
	@echo "... tests/testScheduler.o"
	@echo "... tests/testScheduler.i"
	@echo "... tests/testScheduler.s"
	@echo "... tests/testStack.o"
	@echo "... tests/testStack.i"
	@echo "... tests/testStack.s"
	@echo "... tests/testThread.o"
	@echo "... tests/testThread.i"
	@echo "... tests/testThread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

